In [40]:
import numpy as np
print(np.__version__)
import pandas as pd
print(pd.__version__)

1.20.1
1.2.4


In [12]:
#creating arrays

#np.zeros(5)
#np.ones(5)
#np.full(5,3)
#np.array([5,9,0,12,7])
#np.arange(10)
#np.arange(2,10)
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [18]:
#multi-dimentinal array

#np.zeros((5,2))
n = np.array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])
n[0,1]
n[2]
n[2] = [9,2]
n[:,1]

array([0., 0., 2., 0., 0.])

In [25]:
#Randomly generated arrays

# seed will make the random generated number to be the same as 
# other person using it. The numbers will always e the same
np.random.seed(2)
np.random.rand(5,2)
np.random.randn(5,2)
5 * np.random.rand(5,2)
np.random.randint(low =0, high = 100, size=(5,2))

array([[15,  8],
       [17, 22],
       [73, 57],
       [90, 62],
       [83, 96]])

In [26]:
#Element-wise operations

a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [31]:
a + 1
b = a * 2
b

array([0, 2, 4, 6, 8])

In [34]:
# comparision operations

a >=2
a >= b
# a >= b returns boolean, then the a [] returns which values satisfies 
# this operation
a[a >= b]

array([0])

In [35]:
#Summary

a.min()
a.max()
a.mean()
a.sum()
a.std()

# same thing for multi dimensional arrays

1.4142135623730951

In [44]:
def vector_vector_multiplication(u,v):
    #assert if they are the same size
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    result = 0.0
    
    for i in range(n):
        result = result + u[i] * v[i]
    
    return result
        

In [45]:
vector_vector_multiplication(u,v)

14.0

In [46]:
# similar way to the for loop we can use 
u.dot(v)

14

In [49]:
def matrix_vector_multiplication(U,v):
    assert U.shape[1] ==  v.shape[0]
    
    num_rows = U.shape[0]
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i],v)
    
    return result

In [51]:
matrix_vector_multiplication(M,x)

array([ 54., 100., 317., 366., 454.])

In [67]:
# similar way to the for loop we can use 
M.dot(x)

array([ 54, 100, 317, 366, 454])

In [65]:
def matrix_matrix_multiplication(U,V):
    assert U.shape[1] ==  V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows,num_cols))
    
    for i in range(num_cols):
        vi = V[:,i]
        Uvi = matrix_vector_multiplication (U, vi)
        result[:,i] = Uvi
    
    return result

In [66]:
matrix_matrix_multiplication(M,N)

array([[ 1205.,  1199.,  1141.,   288.,  1434.],
       [ 1883.,  2109.,  2483.,   792.,  2440.],
       [ 6587.,  6883.,  7215.,  2052.,  8117.],
       [ 7790.,  8006.,  8134.,  2232.,  9486.],
       [ 8737.,  9635., 11073.,  3456., 11194.]])

In [68]:
M.dot(N)

array([[ 1205,  1199,  1141,   288,  1434],
       [ 1883,  2109,  2483,   792,  2440],
       [ 6587,  6883,  7215,  2052,  8117],
       [ 7790,  8006,  8134,  2232,  9486],
       [ 8737,  9635, 11073,  3456, 11194]])

In [62]:
#vector operations 

#vectors in numpy are rows instead of columns in linear algebra 

u = np.array([2,4,5,6])
v = np.array([1,0,0,2])
x = np.array([2,3])

# element-wise multiplication
u * v

M = np.array([[15,  8],
       [17, 22],
       [73, 57],
       [90, 62],
       [83, 96]])
N = np.random.randint(low =0, high = 100, size=(2,5))



True

In [69]:
#Identity matrix, I

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [75]:
#Inverse

Vs = M[[0,1]]
Vs

array([[15,  8],
       [17, 22]])

In [76]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 0.11340206, -0.04123711],
       [-0.08762887,  0.07731959]])

In [77]:
Vs_inv.dot(Vs)

array([[ 1.00000000e+00,  0.00000000e+00],
       [-2.22044605e-16,  1.00000000e+00]])